### ISSUE TITLE
Not opening to system tray

### ISSUE THREAD

**Issue by tallos** [planetarian/KCDocumentation#1]
On windows 7 i cannot get it to open or go to the system tray. starting the exe opens and operates it entirely in a command prompt window on the taskbar with no sys tray icon ever showing up and no way to send it to the tray.

**Comment by planetarian** [comment]
Are you using Tibo's release, or mine? If you're using mine, there should be an icon file in the main folder along with the exe. If you're using Tibo's, the icon won't be there, and it won't have the systray functionality.

**Comment by tallos** [comment]
ahh that explains it thanks for the quick reply
